CREATE TABLE IF NOT EXISTS note (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  title VARCHAR(200) NULL,
  note VARCHAR(5000) NULL,
  create_time DATETIME NOT NULL,
  modify_time DATETIME NULL,
  PRIMARY KEY (id));